WIP: Pegs preserve original label
Agoric/ERTP pull request #83
Opened 2019-08-12 04:17 UTC by erights

WIP: Not yet a candidate, as it has not yet been run or tested. However, I'm posting this now as 
   * This updates `makePeg` to be compatible with our new `makeConfig`-based system for making mints and issuers.
   * Scooter is about to depend on this change in behavior.

The peg's new local assay uses the label of the remote issuer, so the amounts it makes are labeled as from that issuer. They are not endorsed by that issuer, but they wouldn't be anyway since they are distant and pass-by-copy. Rather, they coerce to amounts accepted by the remote issuer.

This has pros and cons. 
   * The pros help use of a local peg merely as a bookkeeping advice to track updates to a remotely held escrow purse, as is done in scooter. 
   * The cons are that abstractions, like the escrow exchange that are parameterized by amounts, rather than (issuer,amount) pairs, will extract the intended issuer from the amount, routing around the peg's issuer. Sometimes this will even be intended. When not intended, we'll need to pass (issuer,amount) pairs instead.

2019-08-12 21:02 UTC, Chris-Hibbert requested changes

2019-08-12 21:09 UTC, katelynsills commented on core/issuers.js
> +  let label = harden({ issuer, description });
Maybe if we called this "suggestedLabel" and then called what comes out of makeAssay "label" we might be able to get rid of the comment.

2019-08-13 00:58 UTC, katelynsills commented
> The peg's new local assay uses the label of the remote issuer, so the amounts it makes are labeled as from that issuer.

I think I don't understand the benefit we're getting. It seems confusing to fake a label rather than just use the local label and map it to the remote.

2019-12-02 18:00 UTC, warner commented
this was issue 115 in the old ERTP repo, and part of the "ERTP - Immediate Future" project

2019-12-18 01:19 UTC, erights commented
Obsolete

2019-12-18 01:19 UTC, closed without merging